name: Cypress API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar tests
        run: npx cypress run

      - name: Generar reporte
        if: always()
        run: |
          npm run report:merge
          npm run report:generate

      - name: Subir reporte
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/output.html
